### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by 4TTX** [sooxiaotong/spotify-crack-chrome-app#2]
Hi,

Crack was working fine but few days ago premium button is back and ads doesn't play but freezes spotify.

**Comment by sooxiaotong** [comment]
I just checked, it's still working. Just the upgrade button reappear after they upgraded their UI

**Comment by 4TTX** [comment]
Thanks for your answer.

I dont know if I did something wrong but mine freezes when an Ad is suposed to play.
Please look at the timer "00:30" and freezed.
Already reinstalled and cleared cache, cookies, etc.

https://imgur.com/a/0wBBIVz

**Comment by sooxiaotong** [comment]
are you using the release one or just using the got clone?

**Comment by 4TTX** [comment]
The actual release, decompressed at C:\spotify-crack-chrome-app-master

**Comment by sooxiaotong** [comment]
Try to follow the installation guide, there's some security issue with
chrome that blocked the release version

**Comment by sooxiaotong** [comment]
So can only either use dev or canary version of chrome to get the release version works

**Comment by pms967** [comment]
Does not work anymore here. Spots are back.
